# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/refresh_requester"
      - "/openalex_incremental_updater"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 5
      semver-patch-days: 3
    groups:
      minor-patch-updates:
        update-types: ["minor", "patch"]
      major-updates:
        update-types: ["major"]
    ignore:
      - dependency-name: "setuptools"
