services:
  api:
    build:
      context: ./openalex_incremental_updater
    ports:
      - "8000:8000"
    container_name: openalex-incremental-updater-api
    env_file:
      - openalex_incremental_updater/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check/"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 3s

  job:
    build:
      context: ./refresh_requester
    depends_on:
      api:
        condition: service_healthy
    container_name: refresh-requester
    environment:
      AZURE_CONFIG_DIR: /azcfg
      AZURE_LOG_LEVEL: DEBUG
    volumes:
      - "${HOME}/.azure:/azcfg:rw"
    env_file:
      - refresh_requester/.env
