name: Deploy staging refresh-requester to Azure Container Apps.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  staging-refresh-requester-deploy:
    name: Deploy refresh-requester to staging
    runs-on: ubuntu-latest
    environment: staging

    env:
      IMAGE_NAME: refresh-requester

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to Azure
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to Azure Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        env:
          DOCKER_BUILDKIT: 1
      - run: |
          export TAG=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${TAG} refresh_requester/
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${TAG}

      - name: Deploy to Azure Container App Jobs
        run: |
          export TAG=$(git rev-parse --short HEAD)
          az containerapp job update \
            --name ${{ secrets.CONTAINER_APP_JOB_NAME_STAGING }} \
            --resource-group ${{ secrets.RESOURCE_GROUP_STAGING }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$TAG
