name: Openalex Incremental Updater Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "openalex_incremental_updater/**"

concurrency:
  # Skips intermediate builds and cancels intermediate builds
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  updater-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{matrix.python-version}}
          cache: ""

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.8.9"

      - name: Restore uv cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('openalex_incremental_updater/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('openalex_incremental_updater/uv.lock') }}
            uv-${{ runner.os }}

      - name: Install the project
        working-directory: openalex_incremental_updater
        run: uv sync --locked --all-groups --all-extras --dev

      - name: Run test with pytest via uv
        working-directory: openalex_incremental_updater
        run: uv run pytest --cov=openalex_incremental_updater --cov-report=xml

      - name: Code coverage reporting
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: openalex_incremental_updater/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "80 90"

      - name: Add title to coverage markdown file
        run: |
          echo '## OpenAlex Incremental Updater Coverage' > openalex-incremental-updater-coverage-results.md
          echo '---' >> openalex-incremental-updater-coverage-results.md
          cat code-coverage-results.md >> openalex-incremental-updater-coverage-results.md

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        if: github.event_name == 'pull_request'
        with:
          header: openalex-incremental-updater-coverage
          recreate: true
          path: openalex-incremental-updater-coverage-results.md
