name: Promote refresh-requester to Azure Container Apps production deployment

concurrency: promote-refresh-requester-to-prod

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: refresh-requester

jobs:
  tag-image-for-prod:
    if: github.ref == 'refs/heads/main'
    name: "Add production tag to image"
    runs-on: ubuntu-latest
    environment: production

    outputs:
      unique_tag: ${{ steps.save-tag.outputs.unique_tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tag image with production tag
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        env:
          DOCKER_BUILDKIT: 1
      - run: |
          sha_short=$(git rev-parse --short HEAD)
          unique_tag="${sha_short}-prod"
          docker pull ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${sha_short}
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${sha_short} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${unique_tag}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${unique_tag}
          echo "UNIQUE_TAG=${unique_tag}" >> $GITHUB_ENV
        id: tag-image
      - name: Save unique tag for deployment
        id: save-tag
        run: echo "::set-output name=unique_tag::${{ env.UNIQUE_TAG }}"

  deploy-to-production:
    if: github.ref == 'refs/heads/main'
    name: "Deploy to production"
    runs-on: ubuntu-latest
    needs: [tag-image-for-prod]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy built image to Azure Container App Jobs
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          az containerapp job update \
            --name ${{ secrets.CONTAINER_APP_JOB_NAME_PRODUCTION }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ needs.tag-image-for-prod.outputs.unique_tag }}
